name: Node.js CI

on:
  workflow_dispatch:

  pull_request:
    branches: [main]
    paths:
      - '**.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/*.yml'

  push:
    branches: [main]
    paths:
      - '**.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  ci:
    name: Node.js CI
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: 8

      - name: Setup node environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.10.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run test
        run: pnpm test
